[default]
src = 'src'
out = 'out'
libs = ['lib']

chain_id = 1
eth_rpc_url = 'https://eth-mainnet.alchemyapi.io/v2/{your_alchemy_api_key}'
fork_block_number = 14811771
etherscan_api_key = '{your_etherscan_api_key}'